mainsite_2014/urls.py
from django.conf.urls import patterns, include, url
import os.path
import settings
from mainsite_2014.settings import STATIC_URL
from django.views.generic.simple import redirect_to
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.simple import direct_to_template
# For DajaxIce to work
from misc.dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'erp.views.home', name='home'),
    # url(r'^erp/', include('erp.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^forgot_password/(?P<password_key>.*)/$','users.views.forgot_password'),
    url(r'^forgot_password/success/$','users.views.forgot_password'),
    url(r'^user/register/activate/(?P<a_key>.*)/$','users.views.activate'),
    url(r'^/$', 'frontend.views.home'),#redirect_to, {'url': '/login/'}),
    url(r'^$', 'frontend.views.home'),#redirect_to, {'url': '/login/'}),
    url(r'^tdpsubmission$','users.views.submit_tdp'),
    #url(r'^test/tdpsubmission$','users.views.submit_tdp'),
    url(r'^serenity$', 'frontend.views.serenity'),#redirect_to, {'url': '/login/'}),
    url(r'^files_upload$', 'files_upload.views.upload_file'),
    #url(r'^dashboard$', 'frontend.views.dashboard'),
    #url(r'^dashboard/$', 'frontend.views.dashboard'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT} ),
    url(dajaxice_config.dajaxice_url, include('misc.dajaxice.urls')), # For dajaxice to function corrently
)

#urlpatterns += staticfiles_urlpatterns() # To enable serving static files
    

users/urls.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
import users
import django.contrib.auth.views
#from django.views.generic.simple import redirect_to
from users.views import *
from django.contrib.sites import *
from django.contrib.sitemaps import *
#from sitemaps import *
from django.contrib.sites import *
#from misc.dajaxice.core import dajaxice_autodiscover
from django.conf import settings

#dajaxice_autodiscover()

urlpatterns = patterns(
    '',
    url(r'^login/$', 'users.views.method_splitter', {'GET': login_get,
        'POST': login_post},name='login'),
    url(r'^register/$', 'users.views.method_splitter', {'GET': register_get,
        'POST': register_post}),
    url(r'^logout/$', 'users.views.logout', name='logout'),
	#url(r'^$', redirect_to, {'url': '/user/login/'}),
    #url(r'^user/(?P<username>\w+)/$', 'users.views.myprofileview', name="detail_profile"),
    #url(r'^profile/(?P<username>\w+)/$', 'users.views.myprofileview',name='myprofileview'),
    #url(r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('misc.dajaxice.urls')),
    #url(r'^jayanth/$', 'users.views.myprofileview'),
    
    )
'''#url(r'^admin/password_reset/$',
       'django.contrib.auth.views.password_reset',
    #     name='password_reset'),
    url(r'^password_reset/done/$',
        'django.contrib.auth.views.password_reset_done'),
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm'),
    url(r'^reset/done/$',
        'django.contrib.auth.views.password_reset_complete'),
    url(r'^events/$', 'users.views.events'),
    url(r'^ajax_login/$', ajax_login_link),'''
'''    
# URLs for teams
urlpatterns += patterns('',
    url(r'^teams/(?P<team_id>\d+)/$', team_home),
    url(r'^teams/create/(?P<event_id>\d+)/$', create_team),
    url(r'^teams/(?P<team_id>\d+)/add_member/$', add_member),
    url(r'^teams/(?P<team_id>\d+)/change_leader/$', change_team_leader),
    url(r'^teams/(?P<team_id>\d+)/drop_out/$', drop_out),
    url(r'^teams/(?P<team_id>\d+)/remove_member/$', remove_member),
    url(r'^teams/(?P<team_id>\d+)/dissolve/$', dissolve_team),
    )

#    url(r'^admin/$','users.views.admin', name="super-user"),'''

dashboard/models.py
from django import forms
from django.db import models
from events.models import *
#from users.models import UserProfile
from mainsite_2014.settings import DATABASES
erp_db = DATABASES.keys()[1]
from time import gmtime,strftime
from django.utils import timezone
import datetime,sha,random
#Also set is_active to True each time created
class TeamEvent(models.Model):
    team_id     = models.CharField(default='0',null=True,max_length = 50)
    team_name   = models.CharField(max_length = 30,blank = True,null=True)
    users       = models.ManyToManyField(User, blank = True, null = True)
    is_active   = models.BooleanField(default = False)
    #permissions = models.ManyToManyField(Permission, blank = True, null = True)
    #TODO: add time of adding??
    event_id       = models.IntegerField(default=-1)#This will store id of participant event
    def size(self):
        return len(self.users.all())
        
    def save(self, *args, **kwargs):
        #Here, for event title, TODO:shorthand version of the name needed, for now truncated
        if self.event_id!=-1 and self.is_active == True:
            try:
               event=ParticipantEvent.objects.using(erp_db).get(id=self.event_id)
               self.team_id = 'TEAM#'+ str(event.title[:5])+'#'+str(self.pk)
            except:
                self.team_id = 'TEAM#'+ '#'+str(self.pk)
        super(TeamEvent, self).save(*args, **kwargs)
    def get_event(self):
        try:
            event =  ParticipantEvent.objects.using(erp_db).get(id = self.event_id)    
            return event
        except:
            return None
    def get_team(self):
        uplist = []
        for user in list(self.users.all()):
            up = user.get_profile()
            uplist.append(up)
        return uplist
    def clean(self):
        super(TeamEvent,self).clean()
        try:
            if self.users.count() > ParticipantEvent.objects.using(erp_db).get(id=self.event_id).team_size_max:
                self.is_active = False
            if len(self.users.all())!=len(set(self.users.all())):
                # duplicate users
                self.is_active = False
        except:
            pass
    def __unicode__(self):
        team_str = self.team_id
        if not team_str:
            team_str = "Not provided during registration"
        try:
            event=ParticipantEvent.objects.using(erp_db).get(id=self.event_id)
            return "Team id:%s, Team name: %s, Event:%s" % (self.team_id,team_str,event.title)
        except:
            return "Team id:%s, Team name: %s" % (self.team_id,self.team_name)
    #returns list of tdp's under team
    def get_tdp(self):
        return list(TDP.objects.filter(teamevent = self))
        
    # returns if tdp was submitted
    def has_submitted_tdp(self):
        if len(self.get_tdp()) > 0:
            return True
        return False

#function returns True is user is not in any team given the event id
def has_team(user,event_id = None):
    if event_id is None:
        return 'Need parameter: event id in erpDB','Need parameter: event id in erpDB'
    try:
        event = ParticipantEvent.objects.using(erp_db).get(id = event_id)
        teamEventList = TeamEvent.objects.filter(event_id = event.id)
        for teamevent in teamEventList:
            if user in teamevent.users.all():
                return 'has_team',teamevent.team_name
        return 'no_team','no_team'
    except:
        return 'give proper event id','give proper event id'

#Updates for each user:: The user will get this on login:: He has to approve

UPDATE_CHOICES = (
    ('Team Add', 'Team Add'),
    ('Deadline for Registration', 'Deadline for Registration'),
)

class Update(models.Model):
    tag     = models.CharField(max_length = 20)
    content = models.CharField(max_length = 200)
    user    = models.ForeignKey(User, related_name = 'userupdates')
#    time_added = models.DateTimeField(auto_now = True)
    #link    = models.?? on click user goes to where the update relates to


#ALLOWED_FILETYPE = ['doc','pdf','odt','txt','docx']
ALLOWED_FILETYPE = ['pdf']
def tdp_upload_handler(self,filename):
#    time =  strftime("%a, %d %b %Y %H:%M:%S +0000", gmtime()).replace(" ",'_')
    time = str(timezone.now().date())
    fname = str(filename).split('.')[-1]
    if (fname.split('.')[-1] not in ALLOWED_FILETYPE):
        raise forms.ValidationError("TDP Upload Failed, Use Please only Allowed File Types.")
    if self.file_tdp.size > 5300000:
        raise forms.ValidationError("Maximum File Upload Size is 5MB Exceeded. Given Size: %s MB"% str(self.file_tdp.size*1.0/(1024*1024))[:4])
    #randstr: 5 letter random string to prevent hacking of other team submissions
    randstr = sha.new(str(random.random())).hexdigest()[:5]
    url = 'tdpsubmissions/%s/%s_%s_%s_.%s'%(self.teamevent.get_event().title,self.teamevent.team_id,time,randstr,fname.split('.')[-1])
    #TODO: replace # by something else for url
    url = url.replace('#','_')
    return url


class TDP(models.Model):
    teamevent   = models.ForeignKey(TeamEvent,null = True,blank = True)
    file_tdp    = models.FileField(max_length = 100,upload_to =tdp_upload_handler,blank=True,null=True)
    def save(self,*args,**kwargs):
        if self.teamevent:
            #Check: if registration is not closed:
            if timezone.now()> self.teamevent.get_event().registration_ends:
                return 0
            if self.teamevent.tdp_set.all().count == 0:
                super(TDP,self).save(*args,**kwargs)
            else:
                tdplist = self.teamevent.tdp_set.all()
                #TODO: if invalid type, do NOT delete others, take lite
                super(TDP,self).save(*args,**kwargs)
                #Now, tdplist also contains self, so delete all tdp except existing one
                for tdp in tdplist:
                    if not self == tdp:
                        tdp.delete()
        else:
            super(TDP,self).save(*args,**kwargs)

    def delete(self, *args, **kwargs):
        # You have to prepare what you need before delete the model
        storage, path = self.file_tdp.storage, self.file_tdp.path
        # Delete the model before the file
        super(TDP, self).delete(*args, **kwargs)
        # Delete the file after the model
        storage.delete(path)
        
    def get_event(self):
        if event_id==-1:
            return None
        event = teamevent.get_event()
        return event

    def get_tdp_file(self):
        if self.file_tdp:
            return self.file_tdp
        return None
    
def get_tdp_event(event = None):
    if event is None:
        return None
    if not isinstance(event,ParticipantEvent):
        return None
    tdplist=[]
    for tdp in TDP.objects.using(settings.DATABASES.keys()[0]).all():
        if tdp.get_event() == event:
            tdplist.append((tdp,tdp.teamevent.team_id))
    if len(tdplist) == 0:
        return None
    return tdplist

class TDPFileForm(forms.ModelForm):
    class Meta:
        model = TDP
        exclude = ('teamevent',)
#    def __init__(self, *args, **kwargs):
#        from django.forms.widgets import HiddenInput
#        super(TDPFileForm, self).__init__(*args, **kwargs)
#        self.fields['teamevent'].widget = HiddenInput()

dashboard/views.py
# Create your views here.

templates/dashboard/add_member.html
{% load staticfiles %}
<h3 style='width : 100%;'>
	<span style='left : 25%; display : inline-block;'>Team Member Add to Team {{teamevent.team_name}} for Event {{teamevent.get_event.title}}</span><br/>
	
</h3>

<form action="" class="form-horizontal" method="POST"> {% csrf_token %}
    <label for="add_member_shaastra_id">Enter Shaastra ID:</label>
    <input type="text" value="" placeholder="Shaastra ID of required new member"/ id="new_member_shaastra_id">
    <a class="btn btn-info" onclick="Dajaxice.dashboard.add_member(Dajax.process,{'shaastra_id':$('#new_member_shaastra_id').val(),'teamevent_id':{{teamevent.id}}})">Add member to team!</a>
</form>

templates/dashboard/change_password.html
{% load staticfiles %}
<center>
<h3 style='width : 100%;'>
	<span id='#event_regd_title'>Password Change Form</span>
	&nbsp;
</h3>
<div id="event_registration">
	
		
			<form action="" method="POST" id="form_change_password" class="form-horizontal" > {% csrf_token %}
			<fieldset>
			<table>
                {{form_change_password.as_table}}
			</table>
			</fieldset>
<!--			<div class="form-actions pull-right">-->
				<br/>
				<a id="change_password_submit" class="btn btn-primary" onclick="
				    Dajaxice.users.change_password(Dajax.process, {'form':$('#form_change_password').serialize(true)});
				" class="btn btn-primary ">Change my password</a>
			
<!--			</div>-->
		</form>
</center>
</div>
{% comment %}
{% for i in teammates %}'teammate#{{i}}':$('#shid_{{i}}').val(),{%endfor %}}
{% endcomment %}

templates/dashboard/dash_new.html
{% load dajaxice_templatetags %}
{% load staticfiles %}

<html>
	<head>
		<link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.css' %}" media="all" type="text/css" >
		<link rel="stylesheet" href="{% static 'css/font-awesome.css' %}" media="all" type="text/css" >
		<link rel="stylesheet" href="{% static 'css/style.css' %}" media="all" type="text/css" >
		<link rel="stylesheet" href="{% static 'css/style-responsive.css' %}" media="all" type="text/css" >
		<link rel="stylesheet" href="{% static 'css/base.css' %}" rel="stylesheet">
		<link rel="stylesheet" href="{% static 'css/home/styles.css' %}" type="text/css">
		<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
		<link href="{% static 'css/bootstrap/bootstrap-responsive.min.css' %}" rel="stylesheet">

		<script src="{% static 'js/jquery-1.10.min.2.js' %}"></script>
		<script src="./js/bootstrap.min.js"></script>

		<script src="{% static 'js/jquery/jquery-1.10.2.min.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/jquery.dajax.core.js' %}"></script>
		<script src="{% static 'js/modernizr.custom.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/jquery/jquery.scrollto.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/waypoints.min.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/custom.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/bootstrap/bootstrap.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/bootstrap/bootstrap-tooltip.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/bootstrap/bootstrap-growl.js' %}" type="text/javascript"></script>
		<!--        <script src="{% static 'js/home/hexaflip.js' %}" type="text/javascript"></script>-->
		<script src="{% static 'js/events/boxlayout.js' %}" type="text/javascript"></script>


		{% dajaxice_js_import 'nocsrf' %}
		<title>{% block page_title %}Shaastra | 2014 Participant Dashboard{% endblock %}</title>

	</head>
	<body>
	    {%include 'dashboard/modal_regd.html' %}
		<div class="navbar navbar-inverse navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="brand" href="./index.html">{{request.user.username}}'s Profile</a>
					<div class="nav-collapse collapse pull-right">
						<ul class="nav ">

							<li class="dropdown">
							<a href="#" >REGISTER FOR EVENT <b class="caret"></b></a>
							<!--                        <ul class="dropdown-menu">-->
								<!--                          <li class="nav-header">Robotics</li>-->
								<!--                          <li><a href="#">Robo Event1</a></li>-->
								<!--                          <li><a href="#">Robo Event2</a></li>-->
								<!--                          <li class="divider"></li>-->
								<!--                          <li class="nav-header">Aerobotics</li>-->
								<!--                          <li><a href="#">Aero Event1</a></li>-->
								<!--                          <li><a href="#">Aero Event2</a></li>-->
								<!--                        </ul>-->
							</li>
							<li class="active">
							<a href="./components.html">SHOW MY REGISTERED EVENTS</a>
							</li>
							<li class="">
							<a href="./javascript.html">CHANGE MY PASSWORD</a>
							</li>
							<li class="">
							<a href="./customize.html">GO TO MAINSITE</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
<header class="jumbotron subhead" id="overview">
  <div class="container">
    <h1>Components</h1>
    <br/><br/><br/>
  </div>
</header>
	<div class="container">
		<div class="row">
			<div class="span3 bs-docs-sidebar" id="leftbar_dash">
			    
				<ul class="nav nav-list bs-docs-sidenav affix-top" >
					<li class="active"><a href="#dropdowns"><i class="icon-chevron-right"></i> Dropdowns</a></li>
					<li>
					    <a onclick="Dajaxice.dashboard.register_event_form(Dajax.process,{'event_id':4});" style="cursor:pointer;">Register-For Event ID 4
					    </a>
				    </li>
					<li>
						<a onclick="Dajaxice.users.edit_profile_form(Dajax.process);" style="cursor:pointer;">
							<i class="icon-user icon-white"></i>Edit Profile
						</a>
					</li>
					<li>
						<a onclick="Dajaxice.dashboard.show_registered_events(Dajax.process);" style="cursor:pointer;">Show my registered events
						</a>
					</li>
					<li>
						<a onclick="Dajaxice.users.change_password_form(Dajax.process);" style="cursor:pointer;">Change my password!
					    </a>
					</li>
					<li>
					    <a onclick="Dajaxice.users.show_event_tdp(Dajax.process,{'teamevent_id':25});" style="cursor:pointer;">Submit TDP for event 25
				        </a>
			        </li>
				</ul>
			</div>
			<div class="span9" id="content_dash">
			<ol>
            {%  for up in up_list%}
                <li>{{up.user.first_name}}</li>
            {% endfor %}
            </ol>
    		</div>      
    	</div>
    </div>


</body>
</html>

templates/dashboard/dashboard.html
{% load dajaxice_templatetags %}
{% load staticfiles %}
<html>
    <head>
    <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.css' %}" media="all" type="text/css" >
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}" media="all" type="text/css" >
    <link rel="stylesheet" href="{% static 'css/style.css' %}" media="all" type="text/css" >
    <link rel="stylesheet" href="{% static 'css/style-responsive.css' %}" media="all" type="text/css" >
    <link rel="stylesheet" href="{% static 'css/base.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/home/styles.css' %}" type="text/css">
        <script src="{% static 'js/jquery/jquery-1.10.2.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/jquery.dajax.core.js' %}"></script>
        <script src="{% static 'js/modernizr.custom.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/jquery/jquery.scrollto.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/waypoints.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/custom.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/bootstrap/bootstrap.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/bootstrap/bootstrap-tooltip.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/bootstrap/bootstrap-growl.js' %}" type="text/javascript"></script>
        <!--        <script src="{% static 'js/home/hexaflip.js' %}" type="text/javascript"></script>-->
        <script src="{% static 'js/events/boxlayout.js' %}" type="text/javascript"></script>


        {% dajaxice_js_import 'nocsrf' %}
        <title>{% block page_title %}Shaastra | 2014 Participant Dashboard{% endblock %}</title>
    </head>
    <body>
<!--        {%include 'dashboard/event_registration_form.html' %}-->
        {%include 'dashboard/modal_regd.html' %}
<!--        {%include 'dashboard/profile.html' %}-->
<!--        {%include 'dashboard/registered_events.html' %}-->
        <div class="navbar-wrapper" style="height: auto;">
            <div class="navbar" id="navigation" style="top: 0px;">
            <div class="navbar-header">{{request.user.username}}'s Profile</div>
                <div class="navbar-inner">
                    <button type="button" class="btn btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="nav-collapse collapse">
                        <ul class="nav pull-right" id='navbar_list'>
                            <li><a onclick="Dajaxice.dashboard.register_event_form(Dajax.process,{'event_id':4});" style="cursor:pointer;">Register-For Event ID 4</a></li>
                            <li><a onclick="Dajaxice.users.edit_profile_form(Dajax.process)" style="cursor:pointer;">EDIT PROFILE</a></li>
                            <li><a onclick="Dajaxice.users.show_registered_events(Dajax.process)" style="cursor:pointer;">Show my registered events</a></li>
                            <li><a onclick="Dajaxice.users.change_password_form(Dajax.process)" style="cursor:pointer;">Change my password!</a></li>
                            <li><a href="/" >Go to Main Site</a></li>
                        </ul>
                    </div>
                    {{msg_file_upload}}
                </div>
            </div>
        </div>
    </body>
</html>

templates/dashboard/default.html
Hi {{profile.user.get_full_name}}!<hr>

You have registered for {% if no_regd > 1 %}
<span class="badge badge-success">{{no_regd}}</span> events. Click <a href="#events">here</a> for more!
{% else %}
{% ifequal no_regd 0%}<span class="badge">0</span> events! Click <a href="#events">here</a> to begin!{% endifequal %}{% endif %}
<br/>
<span>Submit your TDP from the option on your sidebar</span>
<br/>
<span>We have some events recommended for you!!</span>
<ul>
{% for event in reco_events %}
<li>{{event.title}}</li>
{% endfor %}
</ul>
{% comment %}
TODO: if he clicks any event, the page will open
{% endcomment %}

templates/dashboard/event_regd_message.html
<h3 style='width : 100%;'>
<center>
	<span id='#show_regd_events_title' style='position:absolute; left : 25%; display : inline-block;'>Message</span>
	&nbsp;
</center>
</h3>
<hr/>
<div class="well">

<span>You need to login to register for an event.<br/> 
                If you do not have an account, fill in the sign up form to create an account and get a Shaastra ID<br/>
                Please take note, obtaining a Shaastra ID does <b>not</b> register you for any event. You are required to fill in the registration form in the individual event's page for this.<br/>
                After logging in, you can register for the event by clicking this same button.</span>
                
</div>

templates/dashboard/event_tdp_submit.html
<h4 style='width : 100%;'>
	<span id='#show_regd_events_title' >{{teamevent.get_event.title}} TDP Submission</span>
	&nbsp;
</h4>

	<hr>
    {% if teamevent.get_event.has_tdp %}

        {% if teamevent.get_event.registration_ends and teamevent.get_event.registration_starts%} 
            {%if now < teamevent.get_event.registration_ends and now > teamevent.get_event.registration_starts%}
                {% comment %}
                TODO: if already uploaded a file, show to view
                {% endcomment %}
                    
                      <h5><span>Note: You can overwrite your previous submission</span></h5>
<!--                    <h4><span>Your submissions:</span></h4>-->
                    
                {% for tdp in teamevent.get_tdp %}
                <h4><a href = "{{settings.MEDIA_URL}}{{tdp.get_tdp_file.name}}" target="_blank" ><u>Download</u></a> Latest Submission :Team {{teamevent.team_name}}</h4>
                {% endfor %}
                
            
            <form action="{{settings.SITE_URL}}tdpsubmission" method="post" enctype="multipart/form-data" id="form_tdp_{{teamevent.get_event.id}}">           {% csrf_token %}
            
                {% if teamevent.has_submitted_tdp %}
                    <span>Please submit only in pdf format. Maximum allowed File Size: 5 MB</span><br/>
<!--                    <span class="btn btn-inverse btn-mini ">-->
                    {{TDPFileForm.as_table}}
                    <center>
                    <br/>
                 
                 </center>
<!--                    </span>-->
                    <input type="hidden" value="{{teamevent.id}}" name="teameventid"/>
                    <br/>
                    <input type="checkbox" id="{{teamevent.id}}_sure" class="pull-left">
				    
                    <label class="control-label">Are you sure you want to overwrite your previous submission? </label>
				    <label class="control-label">&nbsp;&nbsp;&nbsp;&nbsp;It will be deleted!<br/></label><br/>
				    <br/>
				    {% comment %}
<!--				    TODO: check with js the filetype pdf etc-->
				    {% endcomment %}
				    <a class='btn btn-primary' href = "#submit_file" onclick = "
                if($('#form_tdp_{{teamevent.get_event.id}} #id_file_tdp').val()=='')
                {
                    $.bootstrapGrowl('Please submit a file for submission',{'delay':10000});
                }
                
                else
                {
                    if($('#form_tdp_{{teamevent.get_event.id}} #{{teamevent.id}}_sure')[0].checked)
                    {
                        
                        setTimeout(x=function(){$('#file_progress').css({'width':'80%'});}, 1000);
                        $('#form_tdp_{{teamevent.get_event.id}}').submit();
                    }
                    else{
                        $.bootstrapGrowl('Check the radio button to confirm overwriting your previous submission');
                    }
                }
                "
                >Submit {% if teamevent.has_submitted_tdp %} Updated {% endif %}TDP for {{teamevent.get_event.title}}</a>
                {% else %}
<!--                    <span class="btn btn-inverse btn-mini ">-->
                    {{TDPFileForm.as_table}}
                
<!--                    </span>-->
                    <input type="hidden" value="{{teamevent.id}}" name="teameventid"/>
                
                    <a class='btn btn-primary' href = "#submit_file" onclick = "
                if($('#form_tdp_{{teamevent.get_event.id}} #id_file_tdp').val()=='')
                {
                    $.bootstrapGrowl('Please submit a file for submission');
                }
                else
                {
                    
                    $('#form_tdp_{{teamevent.get_event.id}}').submit();
                }
                    "
                    >Submit {% if teamevent.has_submitted_tdp %} Updated {% endif %}TDP for {{teamevent.get_event.title}}</a>
                {% endif %}
            </form>
                
            {% else %}
                {% if now > teamevent.get_event.registration_ends %}
                    {% if teamevent.has_submitted_tdp %}
                    <span>Your submission was received!</span>
                    {% else %}
                    <span>Sorry registrations closed</span>
                    {% endif %}
                {% endif %}
                {% if now < teamevent.get_event.registration_starts %}
                    <span>Please wait, registrations open on {{teamevent.get_event.registration_starts}}</span>
                {% endif %}
            {% endif %}
        {% else %}
            	<span>Registration details not available</span>
        {% endif %}
    {% else %}
    <span>This event has no TDP Submissions</span>
    {% endif %}